# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 073bd57cba6caab7263c56b1feae5b787ac2eacddee2b2004532cea061001dd4bf6808d6ac2390d0906a5784a3f8157ffbfa94f39909a1304c235294de966bf9

test:
  secret_key_base: 7832eb996138435fde2f5bf34b739e75455dd8874abe9448299ac79e1b569b89c2dd0297e1965bb28095978a1a0f1ed1e28ba87295e41623f3c1149fec8e79be

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
